[package]
name = "genome-encryption"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
block-modes = "0.9.1"
cbc = "0.1.2"
cipher = "0.4.4"
flate2 = "1.1.1"
generic-array = "1.2.0"
hex = "0.4.3"
vcf = "0.6.1"
